server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/commerce}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

spring.main.allow-circular-references=false

# OpenAPI Documentation
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Scattered application configs
external.payment.url=http://localhost:8080/mock-payment
external.notification.url=http://localhost:8080/mock-notification
app.order.discount-threshold=100.0
app.order.tax-rate=0.08
app.shipping.flat-rate=15.5
app.payment.mock-provider-name=FastPayMock
